#!/bin/bash

destructive=0
recurse=
manconf=

shopt -s globstar
shopt -s nullglob

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
PURPLE='\033[0;35m'
NC='\033[0m'

while getopts Dhr:f:c flag
do
    case $flag in
    D)  destructive=1;;
    h)  printf "Usage:
    -h  Display this
    -D  Destructive mode (removes the original file after converting)
    -r  Recursion depth (number for depth, i for infinite — DANGEROUS)
    -f  Input format  (e.g. flac)
    -c  Manual confirmation mode (prompt before each file)"; exit;;
    r)  if [ $OPTARG = "i" ] ; then
            recurse=**/
        elif [[ $OPTARG =~ ^[0-9]+$ ]]; then
            recurse=$(for i in $(seq $OPTARG); do
                        printf '%s' "*/"
                    done)
        else
        echo -e "${RED}ERROR${NC}   Invalid input for recurse" && echo "Input either a number for recursion level or i for infinite recursion (DANGEROUS!)\n	f= input format" && exit 1
		fi;;
	f)  format=$OPTARG;;
	c)  manconf=1;;
    ?)  printf "incorrect usage, use -h for help"; exit;;
    esac
done

if [[ -z $format ]]; then
	echo "What format?"
	read format;
fi;

[[ -z "$format" ]] && echo "Empty Format!" && exit 1

for i in $recurse*."$format"; do
    echo -e
    echo -e "${CYAN}$i${NC}"
    wants=y
    if [[ $manconf -eq 1 ]]; then
        read -r -n 1 -t 8 -p "Remux ${i} [Y/N]?" wants
    fi;
    if [[ $wants = [Yy] ]]; then
        if ffmpeg -nostdin -i "$i" -ab 320k -loglevel warning -stats -map_metadata 0 -id3v2_version 3 "${i%.*}.mp3"; then
            echo -e "${GREEN}Success!${NC}"
            if [ $destructive -eq 1 ]; then
                rm -f "$i"
            fi;
        else
            echo -e "${RED}Error${NC}"
        fi;
    fi;
done
