#!/bin/bash
destructive=0
recurse=

shopt -s globstar
shopt -s nullglob

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
PURPLE='\033[0;35m'
NC='\033[0m'

while getopts Dhr:f:R: flag
do
    case $flag in
    D)  destructive=1;;
    h)  printf "Usage \n    h= Display this\n    D= destructive (removes the original file)\n   r= Recursive logic (variable)\n	  f= input format\n	R= target resolution; exit;;
    r)  if [ $OPTARG = "i" ] ; then
            recurse=**/
        elif [[ $OPTARG =~ ^[0-9]+$ ]]; then
            recurse=$(for i in $(seq $OPTARG); do
                        printf '%s' "*/"
                    done)
        else
        echo -e "${RED}ERROR${NC}   Invalid input for recurse" && echo "Input either a number for recursion level or i for infinite recursion (DANGEROUS!)" && exit 1
		fi;;
	f)  format=$OPTARG;;
	R)  res=$OPTARG;;
    ?)  printf "incorrect usage, use -h for help"; exit;;
    esac
done

if [[ -z $format ]]; then
	echo "What format?"
	read format;
fi;

if [[ -z $res ]]; then
	echo "What quality? Input a resolution or use an abreviation such as \"hd720\""
	read res;
fi;


[[ -z "$format" || -z "$res" ]] && echo "Empty Request!" && exit 1


for i in $recurse*."$format"; do
    echo -e
    echo -e
    echo -e "${CYAN}$i${NC}"
    echo -e
    if ffmpeg -i "$i" -loglevel warning -stats -s "$res" "${i%.*}_"$res"."$format""; then
            echo -e "${GREEN}Success!${NC}"
	    if [ $destructive -eq 1 ]; then
            rm -f "$i"
        fi;
    else
        echo -e "${RED}Error${NC}"
    fi;
done


