#!/bin/bash
rmsub=0
rmvid=0
recurse=

shopt -s globstar
shopt -s nullglob

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
PURPLE='\033[0;35m'
NC='\033[0m'

while getopts Ddr:h flag
do
    case $flag in
    D)  rmvid=1;;
    d)  rmsub=1;;
    r)  if [ $OPTARG = "i" ] ; then
            recurse=**/
        elif [[ $OPTARG =~ ^[0-9]+$ ]]; then
            recurse=$(for i in $(seq $OPTARG); do
                        printf '%s' "*/"
                    done)
        else
        echo -e "${RED}ERROR${NC}   Invalid input for recurse" && echo "Input either a number for recursion level or i for infinite recursion (DANGEROUS!)" && exit 1
		fi;;
    h)  printf "Usage \n    h= Display this\n    D= removes the original video once finished\n    d= removes the original subtitle file once finished\n   r= Recursive logic (variable)\n	i= input fomrat\n	o= output format"; exit;;
	i)  from=$OPTARG;;
	o)  to=$OPTARG;;
    ?)  printf "incorrect usage, use -h for help"; exit;;
    esac
done

if [[ -z $format ]]; then
	echo "What format?"
	read format;
fi;

[[ -z "$format" ]] && echo "Empty Format!" && exit 1

for i in $recurse*."$format"; do
    echo -e
    echo -e
    echo -e "${CYAN}$i${NC}"
    echo -e
    if ffmpeg -i "$i" -f srt -i "${i%.*}.srt" -loglevel warning -stats -map 0 -map 1 -c:v copy -c:a copy -c:s mov_text "${i%.*}SUB."$format""; then
            echo -e "${GREEN}Success!${NC}"
	    if [ $rmvid -eq 1 ]; then
            rm -f "$i"
        fi;
        if [ $rmsub -eq 1 ]; then
            rm -f "${i%.*}.srt"
        fi;
    else
        echo -e "${RED}Error${NC}"
    fi;
done



